version: "3.9"

services:

  traefik:
    container_name: thomann_traefik
    build:
      context: .
      dockerfile: traefik/Dockerfile
    ports:
      - 7999:7999
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-public-certificates:/certificates"
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`lookup-traefik.ay-bryson.com`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD}"

  app:
    container_name: thomann_app
    depends_on:
      - redis
    image: ghcr.io/aybry/thomann/thomann:2021-10-11
    # build: .
    command: bash -c "python manage.py migrate --no-input && python manage.py collectstatic --no-input && daphne -b 0.0.0.0 -p 7999 thomann.asgi:application"
    expose:
      - 7999
    environment:
      - DJANGO_SETTINGS_MODULE=thomann.settings.prod
      - THOMANN_DB_HOST=${DBHOST}
      - THOMANN_DB_PORT=${DBPORT}
      - THOMANN_DB_NAME=${DBNAME}
      - THOMANN_DB_SCHEMA=${DBSCHEMA}
      - THOMANN_DB_USERNAME=${DBUNAME}
      - THOMANN_DB_PASSWORD=${DBPASS}
      - THOMANN_SECRET_KEY=${THOMANN_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ~/tlh_backups:/app/backups
      - ~/logs:/app/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asgi.rule=Host(`lookup.ay-bryson.com`)"
      - "traefik.http.routers.asgi.tls=true"
      - "traefik.http.routers.asgi.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.asgi.middlewares=sslheader@docker"

  redis:
    container_name: thomann_redis
    image: redis
    ports:
      - "6380:6379"

volumes:
  static_volume:

networks:
  default:
    external:
      name: thomann_network