[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "web_secure"
        scheme = "https"

  [entryPoints.web_secure]
    address = ":443"

  [entryPoints.websocket_secure]
    address = ":7999"

[accessLog]

[api]
  dashboard = true
  insecure = false

[providers]
  [providers.docker]
    exposedByDefault = false
    watch = true
    network = "thomann_network"

[certificatesResolvers.letsencrypt.acme]
  email = "samuel@ay-bryson.com"
  storage = "/certificates/acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"
