# Generated by Django 3.2.5 on 2021-07-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_hub', '0004_auto_20210729_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='row',
            name='deleted_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_row_set', to='lookup_hub.category'),
        ),
        migrations.AddField(
            model_name='row',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
